---
- name: Install Clickhouse
  hosts: clickhouse-01
  roles:
    - clickhouse

- name: Install Vector
  hosts: vector-01
  roles:
    - vector

- name: Install nginx and ighthouse
  hosts: nginx-lighthouse-01
  roles:
    - lighthouse
